### ISSUE TITLE
Can I simulate spatial patterns with real data?

### ISSUE THREAD

**Issue by VivLon** [ZJUFanLab/scCube#1]
Hi, 

Thanks for your great work! I have a question: Can I simulate spatial patterns with real datasets, or do I have to first simulate a single-cell data with my real data, and then simulate spatial patterns with this simulated single-cell data?

**Comment by ForwardYang98** [comment]
Hi,
Of course you can simulate spatial patterns with real datasets. 
- If you just want to simulate the random spatial patterns through the reference-free strategy, just provide the 'data.csv' (gene expression matrix, with genes as rows and cells as column) and  'meta.csv' (metadata file, with four (or five) columns: Cell, Cell_type, point_x, point_y, (point_z if needed)) files and run the 'generate_pattern_random' function. [Here is a tutorial](https://github.com/ZJUFanLab/scCube/blob/main/tutorial/demo_spot.ipynb)
-  If you want to simulate the real spatial patterns through the reference-based strategy, or simulate the customized spatial patterns through the reference-free strategy, you need to train the VAE model using your datasets first, and then utilized the trained VAE model to generate cells/spots (these simulations would be unattainable using the real data directly, as the number of simulated spatial locations may exceed the number of spots contained in the real data).

**Comment by VivLon** [comment]
Got it. Thank you very much!
