### ISSUE TITLE
How to simulate dataset with several batches?

### ISSUE THREAD

**Issue by VivLon** [ZJUFanLab/scCube#2]
Hi,

I have two questions:
1. I have a scRNA-seq dataset with 3 batches and I want to simulate a spatial dataset preserving the batch effect, is it better to simulate each batch separately or directly simulate the entire dataset?
2. Is the output matrix of scCube logcounts? Do I need further log-normalization before analysis?

Thank you very much!

**Comment by ForwardYang98** [comment]
Hi,
Sorry for the delayed response. I was unfortunately infected with COVID-19 last week so I didn't keep up with the activity on GitHub.
For your questions:
1. I have not previously simulated datasets with batch effects, but I surmise the both of two approaches you mentioned should be able to preserve the batch effect. If you have any results to share, I would be most interested in seeing them!
2. The output matrix of scCube is logcounts and you don't need further log-normalization before analysis.

**Comment by VivLon** [comment]
Sorry to hear that. Hope you are feeling better now.

For the questions:
1. I personally chose to simulate each batch separately, so that I could get a spatial coordinate for each batch, instead of one aligned spatial coordinate for all batches.
2. I've tried selecting 2000 highly variable genes using the simulated data without log-normalization. But it gives "ValueError: cannot specify integer `bins` when input data contains infinity".
https://github.com/scverse/scanpy/issues/2242 The answer in this issue recommends log-normalizing data. I did so and the error didn't appear again. Any suggestions?

**Comment by ForwardYang98** [comment]
Thanks for your feedback.
By default, the scCube‘s VAE framework takes log-normalized data as input, and as a result, the simulated data generated is also log-normalized. You can check if the data is log-normalized before training the VAE model.
Please let me know if you have any further questions or concerns.
